"""Generates `samples/Sample_Test_Package.zip`, a small, entirely
synthetic input with no real borrower or lender data, and
`samples/Sample_Test_Package_Expected_Results.txt`, which documents
exactly what running it through Lender Package Builder should produce.

This exists so a user (or a Windows acceptance tester) can verify a
build is actually working end-to-end without needing any real lender
files: run the app on this ZIP and compare the results against the
expected-results document.

Run with: python samples/generate_sample_package.py
"""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas

SAMPLES_DIR = Path(__file__).resolve().parent
ZIP_PATH = SAMPLES_DIR / "Sample_Test_Package.zip"
EXPECTED_RESULTS_PATH = SAMPLES_DIR / "Sample_Test_Package_Expected_Results.txt"

# A fixed date keeps the ZIP's internal file timestamps deterministic
# across regenerations (the PDF bytes themselves still vary slightly
# run to run because reportlab embeds a creation timestamp/ID -- that
# does not affect processing results, only the raw file bytes).
_FIXED_DATE_TIME = (2024, 1, 1, 0, 0, 0)


def _make_pdf_bytes(lines: list[str], pages: int = 3) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    for page_num in range(1, pages + 1):
        c.setFont("Helvetica", 12)
        y = 700
        c.drawString(72, y, f"Page {page_num} of {pages}")
        for line in lines:
            y -= 20
            c.drawString(72, y, line)
        c.showPage()
    c.save()
    return buf.getvalue()


def generate_sample_package() -> Path:
    loan_disclosure_pdf = _make_pdf_bytes(
        ["Sample Loan Disclosure", "This is synthetic sample content -- not a real document."]
    )

    entries: list[tuple[str, bytes]] = [
        ("Loan_Disclosure.pdf", loan_disclosure_pdf),
        # An exact byte-for-byte duplicate under a different filename --
        # this is what the whole-file SHA-256 exact-duplicate rule
        # should catch: included in OG, excluded from Final.
        ("Loan_Disclosure_Copy.pdf", loan_disclosure_pdf),
        (
            "Borrower_Statement.txt",
            b"Sample Borrower Statement\r\n\r\nThis is synthetic sample content -- not a real document.\r\n",
        ),
        (
            "Additional_Documents/Appraisal_Summary.txt",
            b"Sample Appraisal Summary\r\n\r\nThis is synthetic sample content -- not a real document.\r\n",
        ),
    ]

    ZIP_PATH.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, data in entries:
            info = zipfile.ZipInfo(name, date_time=_FIXED_DATE_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, data)

    return ZIP_PATH


def write_expected_results() -> Path:
    text = """\
Sample_Test_Package.zip -- Expected Results
============================================

This ZIP contains 4 small, entirely synthetic files (no real borrower
or lender data). Running it through Lender Package Builder should
produce the following:

Input contents (4 files):
  - Loan_Disclosure.pdf              (3-page synthetic PDF)
  - Loan_Disclosure_Copy.pdf         (exact duplicate of the file above)
  - Borrower_Statement.txt
  - Additional_Documents/Appraisal_Summary.txt

Expected processing results:
  - Total source documents discovered: 4
  - Exact duplicates detected:          1
      (Loan_Disclosure_Copy.pdf is byte-for-byte identical to
      Loan_Disclosure.pdf and will be flagged as a duplicate)
  - OG package documents:               4  (includes the duplicate)
  - Final package documents:            3  (duplicate excluded)
  - Unconverted/placeholder documents:  0
  - Integrity checks:                   all should PASS
  - Overall result:                     SUCCESS

If your results differ from this -- especially if the duplicate is
not detected, or if any integrity check fails -- something is wrong
with this build and it should not be used on real lender packages
until the problem is understood.

This file and the ZIP it describes are regenerated by
samples/generate_sample_package.py; they contain no real data and can
be freely shared for support/troubleshooting purposes.
"""
    EXPECTED_RESULTS_PATH.write_text(text, encoding="utf-8")
    return EXPECTED_RESULTS_PATH


def main() -> int:
    zip_path = generate_sample_package()
    results_path = write_expected_results()
    print(f"Wrote {zip_path}")
    print(f"Wrote {results_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
