"""Compare Packages engine (MILESTONE 5A).

Compares an Old/Reference package against a New/Generated package --
for the case where a lender package was assembled manually and might
still contain duplicates this app's own pipeline would have caught, or
to confirm a rebuilt package didn't lose or add anything unexplained.

Comparison is strictly analysis-only: neither input is ever modified,
reordered, or written to. This module never touches a filesystem path
it wasn't explicitly given to read.

Reuses the same page-level comparator content_dedup.py already uses
for Level 2-4 duplicate detection (`content_dedup.compare_page`), so
"meaningful difference" here means exactly the same thing it means
everywhere else in this app: differing signatures, dates, dollar
amounts, name-like text, form values, or annotations always veto a
match regardless of how similar the surrounding text looks.

Algorithm: both sides are flattened into one ordered page sequence
(across however many files make up that side), regardless of whether
document boundaries are known -- this is what lets an unbookmarked,
single-PDF manual package be compared at all (see MILESTONE 5's
"UNBOOKMARKED MANUAL PACKAGES" requirement). A cheap `difflib`
alignment on normalized-text hashes finds the "nothing changed" and
"moved as a block" backbone for free; only the pages that alignment
could NOT place get the expensive pairwise `compare_page` treatment,
searched across the *entire* other side (not just the local mismatched
region) so a page that moved far from its original position is still
found.
"""

from __future__ import annotations

import dataclasses
import difflib
import hashlib
import json
from pathlib import Path

from . import naming
from .cancellation import CancellationToken, check_cancelled
from .content_dedup import AUTO_REMOVE_THRESHOLD, NEEDS_REVIEW_THRESHOLD, compare_page
from .inventory import natural_sort_key
from .pdf_content import PageFingerprint, build_document_fingerprint

CATEGORY_EXACT_MATCH = "Exact Match"
CATEGORY_EQUIVALENT_CONTENT = "Equivalent Content"
CATEGORY_DIFFERENT_VERSION = "Same Document, Different Version"
CATEGORY_MEANINGFUL_DIFFERENCE = "Meaningful Difference"
CATEGORY_LIKELY_DUPLICATE_REMOVED = "Likely Duplicate Removed"
CATEGORY_MOVED_OR_REORDERED = "Moved or Reordered"
CATEGORY_ONLY_IN_OLD = "Only in Old"
CATEGORY_ONLY_IN_NEW = "Only in New"
CATEGORY_POSSIBLE_MISSING = "Possible Missing Document"
CATEGORY_EXTRA_PAGE = "Extra Blank, Cover, Index, or Report Page"
CATEGORY_NEEDS_REVIEW = "Needs Review"

_EXTRA_PAGE_MARKERS = (
    "table of contents",
    "index",
    "cover page",
    "generated by",
    "processing report",
    "duplicate removal log",
    "this report",
)
_MIN_MEANINGFUL_TEXT_CHARS = 80


@dataclasses.dataclass
class LoadedPage:
    file_path: Path
    file_label: str
    page_in_file_index: int  # 0-based, within its own file
    overall_index: int  # 0-based, across this side's whole flattened sequence
    fingerprint: PageFingerprint

    @property
    def page_ref(self) -> str:
        return f"{self.file_label}, page {self.page_in_file_index + 1}"


@dataclasses.dataclass
class PackageSide:
    label: str  # "Old / Reference" | "New / Generated"
    files: list[Path]
    pages: list[LoadedPage]

    @property
    def page_count(self) -> int:
        return len(self.pages)


@dataclasses.dataclass
class ComparisonFinding:
    finding_id: str
    category: str
    confidence: float
    old_ref: str | None
    new_ref: str | None
    old_overall_page: int | None
    new_overall_page: int | None
    protected_differences: tuple[str, ...] = ()
    explanation: str = ""
    review_recommended: bool = False


@dataclasses.dataclass
class ComparisonResult:
    old_label: str
    new_label: str
    old_files: list[Path]
    new_files: list[Path]
    old_page_count: int
    new_page_count: int
    findings: list[ComparisonFinding]
    source_hash: str

    def counts_by_category(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for finding in self.findings:
            counts[finding.category] = counts.get(finding.category, 0) + 1
        return counts


@dataclasses.dataclass
class FolderContents:
    """What was found when inspecting a folder selected for comparison
    -- separated so a caller (the GUI) can ask which package set to use
    when both exist, and so extracted key documents/reports are never
    silently swept into a package comparison as if they were whole
    parts.
    """

    final_files: list[Path]
    original_files: list[Path]
    other_pdf_files: list[Path]


def describe_folder_contents(folder: Path) -> FolderContents:
    """Inspects an app-generated output folder (or a plain folder of
    PDFs) and separates its PDFs into Final package parts, Original
    Lender Package parts, and everything else (extracted key documents
    from MILESTONE 4, and anything not matching either naming
    convention) -- reports/manifests are never included since this only
    ever looks at `Final/` (or the folder itself, for a plain folder),
    never `Reports/`.
    """

    final_dir = folder / "Final" if (folder / "Final").is_dir() else folder
    final_files: list[Path] = []
    original_files: list[Path] = []
    other_files: list[Path] = []
    for pdf_path in final_dir.glob("*.pdf"):
        name = pdf_path.stem
        if naming.OG_PACKAGE_KIND in name:
            original_files.append(pdf_path)
        elif naming.FINAL_PACKAGE_KIND in name:
            final_files.append(pdf_path)
        else:
            other_files.append(pdf_path)

    return FolderContents(
        final_files=sort_part_files(final_files),
        original_files=sort_part_files(original_files),
        other_pdf_files=sort_part_files(other_files),
    )


def sort_part_files(file_paths: list[Path]) -> list[Path]:
    """Sorts a set of package-part files into a stable, deterministic
    reading order -- natural sort so "Part 2" comes before "Part 10".
    """

    return sorted(file_paths, key=lambda p: natural_sort_key(p.name))


def load_package_side(label: str, file_paths: list[Path]) -> PackageSide:
    """Flattens one or more PDF files into one ordered page sequence.
    Never modifies any input file -- only reads it.
    """

    files = sort_part_files(list(file_paths))
    pages: list[LoadedPage] = []
    overall = 0
    for file_path in files:
        fingerprint = build_document_fingerprint(str(file_path), file_path)
        for local_index, page_fp in enumerate(fingerprint.pages):
            pages.append(
                LoadedPage(
                    file_path=file_path,
                    file_label=file_path.name,
                    page_in_file_index=local_index,
                    overall_index=overall,
                    fingerprint=page_fp,
                )
            )
            overall += 1
    return PackageSide(label=label, files=files, pages=pages)


def compute_source_hash(old_files: list[Path], new_files: list[Path]) -> str:
    """A stable identity for "this exact pair of inputs, unchanged" --
    used to decide whether a saved comparison can be safely reopened
    without rerunning it (invalidated the instant either side's file
    set or content changes).
    """

    hasher = hashlib.sha256()
    for side_files in (sort_part_files(old_files), sort_part_files(new_files)):
        for file_path in side_files:
            hasher.update(file_path.name.encode("utf-8"))
            hasher.update(str(file_path.stat().st_size).encode("utf-8"))
            hasher.update(hashlib.sha256(file_path.read_bytes()).digest())
        hasher.update(b"|side|")
    return hasher.hexdigest()


def compare_packages(
    old_side: PackageSide, new_side: PackageSide, cancellation_token: CancellationToken | None = None
) -> ComparisonResult:
    old_hashes = [p.fingerprint.text_hash for p in old_side.pages]
    new_hashes = [p.fingerprint.text_hash for p in new_side.pages]
    matcher = difflib.SequenceMatcher(None, old_hashes, new_hashes, autojunk=False)

    findings: list[ComparisonFinding] = []
    matched_old_indices: set[int] = set()
    matched_new_indices: set[int] = set()
    seq = [1]

    unresolved_old: list[LoadedPage] = []
    unresolved_new: list[LoadedPage] = []

    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        check_cancelled(cancellation_token)
        if tag == "equal":
            for offset in range(i2 - i1):
                old_page = old_side.pages[i1 + offset]
                new_page = new_side.pages[j1 + offset]
                matched_old_indices.add(old_page.overall_index)
                matched_new_indices.add(new_page.overall_index)
                findings.append(
                    _finding(seq, CATEGORY_EXACT_MATCH, 1.0, old_page, new_page, "Identical normalized content.")
                )
        elif tag == "replace" and (i2 - i1) == (j2 - j1):
            for offset in range(i2 - i1):
                old_page = old_side.pages[i1 + offset]
                new_page = new_side.pages[j1 + offset]
                matched_old_indices.add(old_page.overall_index)
                matched_new_indices.add(new_page.overall_index)
                findings.append(_compare_pair(seq, old_page, new_page))
        else:
            unresolved_old.extend(old_side.pages[i1:i2])
            unresolved_new.extend(new_side.pages[j1:j2])

    # Every unresolved page is searched across the OTHER side's ENTIRE
    # sequence (not just its local mismatched region), so a page moved
    # far from its original position is still found -- see
    # CATEGORY_MOVED_OR_REORDERED below.
    for old_page in unresolved_old:
        check_cancelled(cancellation_token)
        findings.append(
            _resolve_unmatched(seq, old_page, new_side, matched_new_indices, old_side, matched_old_indices, is_old=True)
        )
    for new_page in unresolved_new:
        check_cancelled(cancellation_token)
        findings.append(
            _resolve_unmatched(seq, new_page, old_side, matched_old_indices, new_side, matched_new_indices, is_old=False)
        )

    findings.sort(key=lambda f: (f.old_overall_page if f.old_overall_page is not None else 10**9, f.new_overall_page or 0))

    return ComparisonResult(
        old_label=old_side.label,
        new_label=new_side.label,
        old_files=old_side.files,
        new_files=new_side.files,
        old_page_count=old_side.page_count,
        new_page_count=new_side.page_count,
        findings=findings,
        source_hash=compute_source_hash(old_side.files, new_side.files),
    )


def _next_id(seq: list[int]) -> str:
    finding_id = f"CMP-{seq[0]:04d}"
    seq[0] += 1
    return finding_id


def _finding(
    seq: list[int],
    category: str,
    confidence: float,
    old_page: LoadedPage | None,
    new_page: LoadedPage | None,
    explanation: str,
    protected_differences: tuple[str, ...] = (),
    review_recommended: bool = False,
) -> ComparisonFinding:
    return ComparisonFinding(
        finding_id=_next_id(seq),
        category=category,
        confidence=confidence,
        old_ref=old_page.page_ref if old_page else None,
        new_ref=new_page.page_ref if new_page else None,
        old_overall_page=old_page.overall_index if old_page else None,
        new_overall_page=new_page.overall_index if new_page else None,
        protected_differences=protected_differences,
        explanation=explanation,
        review_recommended=review_recommended,
    )


def _compare_pair(seq: list[int], old_page: LoadedPage, new_page: LoadedPage) -> ComparisonFinding:
    result = compare_page(old_page.fingerprint, new_page.fingerprint, old_page.file_path, new_page.file_path)
    if result.hard_veto:
        return _finding(
            seq,
            CATEGORY_MEANINGFUL_DIFFERENCE,
            0.0,
            old_page,
            new_page,
            f"Protected difference: {result.veto_reason}.",
            protected_differences=(result.veto_reason or "unspecified",),
            review_recommended=True,
        )
    if result.confidence >= AUTO_REMOVE_THRESHOLD:
        category = CATEGORY_EXACT_MATCH if result.confidence >= 0.999 else CATEGORY_EQUIVALENT_CONTENT
        return _finding(seq, category, result.confidence, old_page, new_page, "Same content, high confidence.")
    if result.confidence >= NEEDS_REVIEW_THRESHOLD:
        return _finding(
            seq,
            CATEGORY_DIFFERENT_VERSION,
            result.confidence,
            old_page,
            new_page,
            "Similar but not confidently identical content -- may be a revised version.",
            review_recommended=True,
        )
    return _finding(
        seq,
        CATEGORY_MEANINGFUL_DIFFERENCE,
        result.confidence,
        old_page,
        new_page,
        "Content differs beyond the safe-match threshold.",
        review_recommended=True,
    )


def _resolve_unmatched(
    seq: list[int],
    page: LoadedPage,
    other_side: PackageSide,
    other_matched_indices: set[int],
    own_side: PackageSide,
    own_matched_indices: set[int],
    is_old: bool,
) -> ComparisonFinding:
    best_match: LoadedPage | None = None
    best_confidence = 0.0
    for candidate in other_side.pages:
        if candidate.overall_index in other_matched_indices:
            # Already accounted for by another finding -- matching this
            # page against it too would double-count one page on the
            # other side as "moved" to explain two different pages here.
            continue
        result = compare_page(
            page.fingerprint, candidate.fingerprint,
            page.file_path if is_old else candidate.file_path,
            candidate.file_path if is_old else page.file_path,
        )
        if result.hard_veto:
            continue
        if result.confidence > best_confidence:
            best_confidence = result.confidence
            best_match = candidate

    if best_match is not None and best_confidence >= AUTO_REMOVE_THRESHOLD:
        old_page, new_page = (page, best_match) if is_old else (best_match, page)
        # Marked matched immediately (both sides) so a later unresolved
        # page can never also claim this same candidate as its own move,
        # and so this page counts as "accounted for" for duplicate-
        # removal detection below.
        other_matched_indices.add(best_match.overall_index)
        own_matched_indices.add(page.overall_index)
        return _finding(
            seq,
            CATEGORY_MOVED_OR_REORDERED,
            best_confidence,
            old_page,
            new_page,
            "Same content found at a different position in the other package.",
        )

    if _looks_like_extra_page(page.fingerprint):
        old_page, new_page = (page, None) if is_old else (None, page)
        return _finding(
            seq, CATEGORY_EXTRA_PAGE, 0.5, old_page, new_page,
            "Looks like a cover/index/report page rather than borrower content.",
        )

    # A near-duplicate of another page ALREADY matched on this same side
    # suggests the OTHER copy correctly survived and this one was a
    # redundant duplicate -- not truly missing content.
    if is_old:
        for candidate_index in own_matched_indices:
            candidate = own_side.pages[candidate_index]
            result = compare_page(page.fingerprint, candidate.fingerprint, page.file_path, candidate.file_path)
            if not result.hard_veto and result.confidence >= AUTO_REMOVE_THRESHOLD:
                return _finding(
                    seq, CATEGORY_LIKELY_DUPLICATE_REMOVED, result.confidence, page, None,
                    f"Near-duplicate of {candidate.page_ref}, which is already accounted for.",
                )

    if is_old:
        return _finding(
            seq, CATEGORY_POSSIBLE_MISSING, 0.3, page, None,
            "No matching content found anywhere in the new package.",
            review_recommended=True,
        )
    return _finding(
        seq, CATEGORY_ONLY_IN_NEW, 0.3, None, page,
        "No matching content found anywhere in the old package.",
        review_recommended=True,
    )


def write_comparison_report(result: ComparisonResult, path: Path) -> None:
    """`Package Comparison Report.txt` -- a human-readable finding-by-
    finding record. Never written into either input package itself;
    the caller chooses a separate comparison-results folder or Reports.
    """

    lines: list[str] = []
    lines.append("PACKAGE COMPARISON REPORT")
    lines.append("=" * 70)
    lines.append(f"Old / Reference package: {result.old_label} ({result.old_page_count} page(s))")
    for f in result.old_files:
        lines.append(f"    - {f.name}")
    lines.append(f"New / Generated package: {result.new_label} ({result.new_page_count} page(s))")
    for f in result.new_files:
        lines.append(f"    - {f.name}")
    lines.append("")
    lines.append("Summary by category:")
    for category, count in sorted(result.counts_by_category().items(), key=lambda kv: -kv[1]):
        lines.append(f"    {category}: {count}")
    lines.append("")
    lines.append(
        "This comparison is analysis-only -- neither package above was modified, reordered, "
        "or written to."
    )
    lines.append("")

    for finding in result.findings:
        lines.append("=" * 70)
        lines.append(f"{finding.finding_id}: {finding.category} (confidence {finding.confidence:.2f})")
        lines.append("=" * 70)
        lines.append(f"    Old: {finding.old_ref or '(not present)'}")
        lines.append(f"    New: {finding.new_ref or '(not present)'}")
        if finding.protected_differences:
            lines.append(f"    Protected differences: {', '.join(finding.protected_differences)}")
        lines.append(f"    {finding.explanation}")
        if finding.review_recommended:
            lines.append("    Recommendation: review this finding directly before relying on it.")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def _json_default(obj):
    if isinstance(obj, Path):
        return str(obj)
    raise TypeError(f"Object of type {type(obj)} is not JSON serializable")


def write_comparison_manifest(result: ComparisonResult, path: Path) -> None:
    """`Package Comparison Manifest.json` -- the complete machine-
    readable record, including `source_hash` so a saved comparison can
    be safely reopened later only if neither input has changed since
    (see `compute_source_hash`).
    """

    manifest = {
        "old_label": result.old_label,
        "new_label": result.new_label,
        "old_files": [str(f) for f in result.old_files],
        "new_files": [str(f) for f in result.new_files],
        "old_page_count": result.old_page_count,
        "new_page_count": result.new_page_count,
        "source_hash": result.source_hash,
        "counts_by_category": result.counts_by_category(),
        "findings": [dataclasses.asdict(f) for f in result.findings],
    }
    path.write_text(json.dumps(manifest, indent=2, default=_json_default), encoding="utf-8")


def _looks_like_extra_page(fp: PageFingerprint) -> bool:
    text = fp.normalized_text.casefold()
    if fp.blank.is_blank:
        return True
    if len(text) < _MIN_MEANINGFUL_TEXT_CHARS and not fp.form_fields and not fp.images:
        return True
    return any(marker in text for marker in _EXTRA_PAGE_MARKERS)
